\mainmatter

# 导言 {#intro}

2018年12月教育部等九部门印发中小学生减负措施的通知，要求切实减轻违背教育教学规律、有损中小学生身心健康的过重学业负担，促进中小学生健康成长，培养德智体美劳全面发展的社会主义建设者和接班人。我区坚持学生课业负担年度调查，了解相关减负政策的落实情况。2019年6月，对全区四、五、七年级的学生进行了学生课业负担状况问卷调查，分别收到有效数据7912、8018、5146份。本次学生课业负担状况主要考查学生的课业负担状况（包括客观课业负担和主观学习感受）和相关影响因素。通过主客观负担和影响因素数据的呈现，以及分析课业负担、学习方法、学习成绩三者的关联，进一步分析落实减轻学生学业负担、提高学生学习深度的有效路径。

本站《成语故事》收录了五千多个经典成语故事，如八仙过海、画龙点睛、守株待兔、一箭双雕等，都是我们耳熟能详的。成语故事按成语首字读音顺序排列，以故事形式对成语的出处、典故、含义进行清晰明了的解释，故事通俗易懂、内涵深刻、妙趣无穷，真实地再现了一段段传奇往事和历史遗痕。

## 第一节

如果汉语是浩瀚的大海，成语就是其中美丽的贝壳，成语故事就是贝壳里的珍珠。成语作为语言的精华、历史的缩影、文明的积淀、智慧的浓缩，处处闪烁着睿智的光芒，是中华民族的文化瑰宝。成语故事则是历史文化的智慧凝结，是各个历史时代的产物，蕴含着丰富的历史知识和深刻的道理。

本站《成语故事》收录了五千多个经典成语故事，如八仙过海、画龙点睛、守株待兔、一箭双雕等，都是我们耳熟能详的。成语故事按成语首字读音顺序排列，以故事形式对成语的出处、典故、含义进行清晰明了的解释，故事通俗易懂、内涵深刻、妙趣无穷，真实地再现了一段段传奇往事和历史遗痕。

## 第二节

如果汉语是浩瀚的大海，成语就是其中美丽的贝壳，成语故事就是贝壳里的珍珠。成语作为语言的精华、历史的缩影、文明的积淀、智慧的浓缩，处处闪烁着睿智的光芒，是中华民族的文化瑰宝。成语故事则是历史文化的智慧凝结，是各个历史时代的产物，蕴含着丰富的历史知识和深刻的道理。



　　


本次学生学业负担评价指标如下表\@ref(tab:zb)所示：



```{r zb}
read_csv(here::here("data", "zb.csv")) %>%
  knitr::kable(
    "latex",
    booktabs = TRUE,
    caption = "评价指标"
  )
```




如果汉语是浩瀚的大海，成语就是其中美丽的贝壳，成语故事就是贝壳里的珍珠。成语作为语言的精华、历史的缩影、文明的积淀、智慧的浓缩，处处闪烁着睿智的光芒，是中华民族的文化瑰宝。成语故事则是历史文化的智慧凝结，是各个历史时代的产物，蕴含着丰富的历史知识和深刻的道理。

本站《成语故事》收录了五千多个经典成语故事，如八仙过海、画龙点睛、守株待兔、一箭双雕等，都是我们耳熟能详的。成语故事按成语首字读音顺序排列，以故事形式对成语的出处、典故、含义进行清晰明了的解释，故事通俗易懂、内涵深刻、妙趣无穷，真实地再现了一段段传奇往事和历史遗痕。

本站《成语故事》收录了五千多个经典成语故事，如八仙过海、画龙点睛、守株待兔、一箭双雕等，都是我们耳熟能详的。成语故事按成语首字读音顺序排列，以故事形式对成语的出处、典故、含义进行清晰明了的解释，故事通俗易懂、内涵深刻、妙趣无穷，真实地再现了一段段传奇往事和历史遗痕。
